baseURL: https://armannd092.github.io

languageCode: en-us
title: "Arman"
theme: "toha"

# Allow raw html in markdown file
permalinks:
  portfolio: /portfolio/:title/
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: <your site's google analytics id>
# Enable Disqus forum
disqusShortname: <your site's disqus short code>

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # copyright
  copyright: © 2020 Copyright.

  # background image of the landing page
  background: "images/webcover.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: /assets/images/Logo.png
    inverted: /assets/images/invert-Logo.png

  # GitHub repo URL of your site
  gitRepo: <your site's Github repo URL>

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  enablePortfolio: true  

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  #customMenus:
  #- name: Notes
  #  url: <your custom menu link>

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
  #For adding hrml tags in markup  
  markup:
  goldmark:
    renderer:
      unsafe: true
  # some information about you
  author:
    name: "Arman"
    nickname: "Arman"
    image: "images/myavatar.png"
    # give your contact information. they will be used in the footer
    contactInfo:
      email: "armannd092.com"
      phone: "+34677648445"
    # a summary of what you do
    summary:
    - I am a designer
    - I am a fabricator
    - I love to make fun projects